# Generated by Django 2.1.3 on 2018-12-01 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20181201_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upload',
            field=models.FileField(upload_to=''),
        ),
    ]
